// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Article struct {
	ID        int64
	Title     string
	Body      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
