// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Article struct {
	ID        int64         `json:"id"`
	Title     string        `json:"title"`
	Body      string        `json:"body"`
	CreatedAt sql.NullInt64 `json:"created_at"`
	UpdatedAt sql.NullInt64 `json:"updated_at"`
}
